---
title: "Mansuy"
author: "Noé Mansuy"
format: html
---
Github repository : https://github.com/Noenmk/grades-eval.git

## 1 - Introduction

```{r}
library(here)
library(ggplot2)
library(vroom)
library(dplyr)
library(tidyr)
here::i_am("grades-eval.Rproj")
```
# Question 1

```{r}
courses <- vroom(here("courses.csv"))
```
# Question 2 
```{r}
courses_formatted_table <- courses |> 
  arrange(course) |> 
  select(
    'course name' = course,
    identifier = course_id,
    module = module,
    'number of exams' = nb_grades
  )
courses_formatted_table |> 
  knitr::kable()
```
# Question 3
```{r}
students <- vroom(
  here("students.csv"),
  col_types = cols(
    id = col_integer(),
    group = col_integer(), 
    birth_date = col_date(format = "%Y-%m-%d"), 
    sex = col_factor()
  )
)

print(paste("The birth_date column of the students data frame is of class",
            class(students$birth_date)))
print(paste("The sex column of the students data frame is of class",
            class(students$sex)))
```
# Question 4

```{r}
grades <- vroom(here("grades.csv"), 
  delim = ":", 
  na = "_", 
  col_types = cols(
    id = col_integer(),
    course_id = col_factor(),
    grade = col_double()
  )
)
```

## Student population analysis

# Question 5
```{r}
students |> 

  ggplot(aes(x = group)) + 
  
  geom_bar(fill = "steelblue") +
  
  labs(
    title = "Distribution of Students Across Groups",
    x = "Student Group ",
    y = "Number of Students"
  ) 
```

# Question 6

```{r}
students |>
  
  ggplot(aes(x = group, fill = sex)) +
  
 
  geom_bar(position = "fill") +
  
  labs(
    title = "Gender Balance by Student Group",
    x = "Student Group ",
    y = "Proportion of Students ",
    fill = "Gender"
  )
```
# Question 7


```{r}
library(lubridate)
students |>
  
  mutate(
    age_years = time_length(today() - birth_date, unit = "year")
  ) |>
  
  ggplot(aes(x = age_years)) +
  
  geom_histogram(fill = "darkgreen", color = "white") +
  
  labs(
    title = "Distribution of Student Age",
    x = "Age (Years)",
    y = "Number of Students"
  )
```
# Question 8


```{r}
# Juste le calcul
median_age_table <- students |>
  group_by(group) |> 
  mutate(
    age_years = time_length(today() - birth_date, unit = "year")
  ) |>
  summarize(
    median_age_int = floor(median(age_years, na.rm = TRUE))
  )

# Affichage du tableau proprement
median_age_table |>
  select(
    'Group Identifier' = group,
    'Median Age' = median_age_int
  ) |>
  knitr::kable()

```
# Question 9

```{r}

oldest_students <- students |>
  mutate(age = floor(time_length(today() - birth_date, unit = "year"))) |>
  
  group_by(group) |>
  slice_max(age, n = 1, with_ties = FALSE) |>
  
  select(id, sex, age) |>
  
  arrange(desc(age))
knitr::kable(oldest_students)

```
## Simple grade analysis

# Question 10

The data set grades contains `r sum(!is.na(grades$grade))` grades.

# Question 11

```{r}
combined_data <- grades |> 
  left_join(courses, by = "course_id") |>

  left_join(students, by = "id")

avg_grades_table <- combined_data |>
  
  filter(course == "Traditional Medicine and Herbalism") |>
  
  group_by(group) |>
  
  summarize(
    avg_grade = mean(grade, na.rm = TRUE)
  )

avg_grades_table |>
  mutate(group = factor(as.integer(as.character(group)), ordered = TRUE)) |>
  ggplot(aes(x = group, y = avg_grade)) + 
  geom_col(fill = "salmon", color = "white") +
  geom_hline(yintercept = mean(avg_grades_table$avg_grade, na.rm = TRUE), 
             linetype = "dashed", color = "grey20") +
  scale_y_continuous(limits = c(0, 20)) +  # <-- set y-axis from 0 to 20
  labs(
    title = "Average Grade in Traditional Medicine and Herbalism by Group",
    x = "Student Group",
    y = "Average Grade"
  )

  
```






